/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulbra.br.view;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Random;

/**
 *
 * @author Aluno.saolucas
 */
public class ProjetoFinal extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoFinal
     */
    public ProjetoFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
        painelresposta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup6 = new javax.swing.ButtonGroup();
        checkbox1 = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        painelresposta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRNome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRSigno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRDescricao = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRIdade = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRCor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        cbMes = new javax.swing.JComboBox<>();
        cbDia = new javax.swing.JComboBox<>();
        lbDescubra = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        txtAno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 172, 137));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNome.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome completo:");
        jPanel1.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 250, 30));

        painelresposta.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESULTADO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Nome");

        txtRNome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Signo");

        txtRSigno.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("Descrição");

        txtRDescricao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("Idade:");

        txtRIdade.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Cor");

        txtRCor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelrespostaLayout = new javax.swing.GroupLayout(painelresposta);
        painelresposta.setLayout(painelrespostaLayout);
        painelrespostaLayout.setHorizontalGroup(
            painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelrespostaLayout.createSequentialGroup()
                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelrespostaLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(painelrespostaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelrespostaLayout.createSequentialGroup()
                                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelrespostaLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelrespostaLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(50, 50, 50)))
                                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(painelrespostaLayout.createSequentialGroup()
                                        .addComponent(txtRIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(painelrespostaLayout.createSequentialGroup()
                                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelrespostaLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtRSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelrespostaLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtRNome, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addGroup(painelrespostaLayout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(59, 59, 59)
                                            .addComponent(txtRCor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 43, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        painelrespostaLayout.setVerticalGroup(
            painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelrespostaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtRIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelrespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRCor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(painelresposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 620, 460));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 430, 30));

        lbSexo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(255, 255, 255));
        lbSexo.setText("Sexo:");
        jPanel1.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        btConsultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 120, 40));

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 120, 40));

        cbMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });
        jPanel1.add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 40));

        cbDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiaActionPerformed(evt);
            }
        });
        jPanel1.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, 40));

        lbDescubra.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbDescubra.setForeground(new java.awt.Color(255, 255, 255));
        lbDescubra.setText("Descubra seu signo");
        jPanel1.add(lbDescubra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 550, 80));

        lbData.setBackground(new java.awt.Color(255, 255, 255));
        lbData.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbData.setForeground(new java.awt.Color(255, 255, 255));
        lbData.setText("Data de nascimento:");
        jPanel1.add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 290, 30));

        cbSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanel1.add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 120, 40));

        txtAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAno.setText("Ano");
        txtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/zo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 1150, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed


    }//GEN-LAST:event_txtNomeActionPerformed
    public static String obterDescricaoSigno(String signo) {
        switch (signo) {
            case "Aquário":
                return "Inovador, original e independente.";
            case "Peixes":
                return "Compassivo, artístico e intuitivo.";
            case "Áries":
                return "Corajoso, determinado e confiante.";
            case "Touro":
                return "Confiável, paciente e devoto.";
            case "Gêmeos":
                return "Adaptável, comunicativo e curioso.";
            case "Câncer":
                return "Tenaz, altamente imaginativo e leal.";
            case "Leão":
                return "Criativo, apaixonado e generoso.";
            case "Virgem":
                return "Leal, analítico e trabalhador.";
            case "Libra":
                return "Cooperativo, diplomático e gracioso.";
            case "Escorpião":
                return "Apaixonado, determinado e assertivo.";
            case "Sagitário":
                return "Generoso, idealista e grande senso de humor.";
            case "Capricórnio":
                return "Responsável, disciplinado e autocontrole.";
            default:
                return "Descrição não disponível.";
        }
    }

    public int calcularIdade(int dia, int mes, int ano) {
        Calendar hoje = Calendar.getInstance();
        int diaAtual = hoje.get(Calendar.DAY_OF_MONTH);
        int mesAtual = hoje.get(Calendar.MONTH) + 1;
        int anoAtual = hoje.get(Calendar.YEAR);
        int idade;

        idade = ((anoAtual * 365 + mesAtual + 12 + diaAtual) - (ano * 365 + mes * 12 + dia)) / 365;

        return idade;
        /* if (mesAtual < get.cbMes || (mesAtual == mes && diaAtual < dia)) {
            idade--;
        }*/
    }

    public String gerarCor() {
        String[] cores = {"vermelho", "verde", "azul", "amarelo", "roxo", "violeta", "laranja", "marrom", "preto", "branco"};
        Random ncor = new Random();
        int c = ncor.nextInt(9);
        return cores[c];
    }

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        String nome = txtNome.getText();
        //nome = nome.replaceAll(" ", "");
        int tamanho = nome.length();
        if (tamanho < 8) {
            JOptionPane.showMessageDialog(this, "Bonito o nome, pena que ele não é verdadeiro");
        } else {
            String signo = "";
            int dia, mes, ano;
            dia = cbDia.getSelectedIndex();
            mes = cbMes.getSelectedIndex();
            ano = Integer.parseInt(txtAno.getText());
            Calendar hoje = Calendar.getInstance();
            int anoAtual = hoje.get(Calendar.YEAR);
            if (ano >= 1900 && ano <= anoAtual) {
                if ((mes == 1 && dia >= 21 && dia <= 31) || (mes == 2 && dia >= 1 && dia <= 19)) {
                    signo = "Aquario";
                } else if ((mes == 2 && dia >= 20 && dia <= 28) || (mes == 3 && dia >= 1 && dia <= 20)) {
                    signo = "Peixes";
                } else if ((mes == 3 && dia >= 21 && dia <= 31) || (mes == 4 && dia >= 1 && dia <= 20)) {
                    signo = "Áries";
                } else if ((mes == 4 && dia >= 21 && dia <= 30) || (mes == 5 && dia >= 1 && dia <= 20)) {
                    signo = "Touro";
                } else if ((mes == 5 && dia >= 21 && dia <= 31) || (mes == 6 && dia >= 1 && dia <= 20)) {
                    signo = "Gêmeos";
                } else if ((mes == 6 && dia >= 21 && dia <= 30) || (mes == 7 && dia >= 1 && dia <= 21)) {
                    signo = "Câncer";
                } else if ((mes == 7 && dia >= 22 && dia <= 31) || (mes == 8 && dia >= 1 && dia <= 22)) {
                    signo = "Leão";
                } else if ((mes == 8 && dia >= 23 && dia <= 31) || (mes == 9 && dia >= 1 && dia <= 22)) {
                    signo = "Virgem";
                } else if ((mes == 9 && dia >= 23 && dia <= 30) || (mes == 10 && dia >= 1 && dia <= 22)) {
                    signo = "Libra";
                } else if ((mes == 10 && dia >= 23 && dia <= 31) || (mes == 11 && dia >= 1 && dia <= 21)) {
                    signo = "Escorpião";
                } else if ((mes == 11 && dia >= 22 && dia <= 30) || (mes == 12 && dia >= 1 && dia <= 21)) {
                    signo = "Sagitário";
                } else if ((mes == 12 && dia >= 22 && dia <= 31) || (mes == 1 && dia >= 1 && dia <= 20)) {
                    signo = "Capricórnio";
                   
                }else{
                    signo = "Data invalida";
                }
                painelresposta.setVisible(true);
                txtRNome.setText(nome);
                txtRSigno.setText(signo);
                txtRDescricao.setText(obterDescricaoSigno(signo));
                txtRCor.setText(gerarCor());
                txtRIdade.setText(calcularIdade(dia, mes, ano)+" anos ");
                //JOptionPane.showMessageDialog(null, nome + " Você tem " + calcularIdade(dia, mes, ano)
                  //      + " anos de idade. Seu signo é " + signo +". " 
                    //    +obterDescricaoSigno(signo)+"\n Sua cor da sorte é " + gerarCor() );

            } else {
                JOptionPane.showMessageDialog(null, "Informe um ano entre 1900 e o ano atual");
            }

        }


    }//GEN-LAST:event_btConsultarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtNome.setText(null);

    }//GEN-LAST:event_btLimparActionPerformed

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    private void cbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiaActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          painelresposta.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbSexo;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbDescubra;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JPanel painelresposta;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtRCor;
    private javax.swing.JLabel txtRDescricao;
    private javax.swing.JLabel txtRIdade;
    private javax.swing.JLabel txtRNome;
    private javax.swing.JLabel txtRSigno;
    // End of variables declaration//GEN-END:variables
}
